name: Port Submission
description: Submit a candidate Android port for the PS Vita SO loader
title: "[Android Game Name]: "
labels: ["bug", "triage"]
assignees:
  - CatoTheYounger
body:
- type: checkboxes
  id: rules
  attributes:
    label: Submission Rules
    description: By submitting this candidate, you have read the README.md and understand the submission rules. 
    options:
      - label: I have read the README.md and understand the submission rules. 
    validations:
      required: true
- type: checkboxes
  id: nounity
  attributes:
    label: Unity Games
    description: The README.md states that games made in Unity are not suitable candidates. 
    options:
      - label: I have checked this game is not made in Unity and does not contain a libunity.so.
    validations:
      required: true
- type: input
  id: gamename
  attributes:
    label: Game Name
    description: "Name of the Android game."
  validations:
    required: true
- type: input
  id: gameversion
  attributes:
    label: Game Version
    description: "Version number of the Android game."
  validations:
    required: true
- type: input
  id: store
  attributes:
    label: Store Link
    description: "Please enter an Amazon App Store or Google Play link to the game. If this is not possible, write: delisted"
  validations:
    required: true
- type: dropdown
  id: armversion
  attributes:
    label: ARM Build Version
    description: What version of our software are you running?
    options:
      - ARMv6
      - ARMv7
  validations:
    required: true
- type: dropdown
id: armversion
attributes:
  label: ARM Build Version
  description: What version of our software are you running?
  options:
    - GLES1
    - GLES2
    - GLES3+
validations:
  required: true
- type: textarea
  id: comment
  attributes:
    label: Relevant Information
    description: "comment box."
