name: Port Submission
description: Submit a candidate Android port for the PS Vita SO loader
title: "[Android Game Name]: "
labels: ["submission"]
assignees:
  - CatoTheYounger
body:
  - type: checkboxes
    id: rules
    attributes:
      label: Submission Rules
      description: By submitting this candidate, you have read the README.md and understand the submission rules
      options:
        - label: I have read the README.md and understand the submission rules
          required: true
  - type: checkboxes
    id: nounity
    attributes:
      label: Unity Games
      description: The README.md states that games made in Unity are not suitable candidates
      options:
        - label: I have checked this game is not made in Unity and does not contain a libunity.so
          required: true

  - type: input
    id: gamename
    attributes:
      label: Game Name
      description: Name of the Android game
    validations:
      required: true
