name: Port Submission
description: Submit a candidate Android port for the PS Vita SO loader
title: "[Android Game Name]: "
labels: ["bug", "triage"]
assignees:
  - CatoTheYounger
body:
  - type: checkboxes
  id: rules
  attributes:
    label: Submission Rules
    description: By submitting this candidate, you have read the README.md and understand the submission rules. 
    options:
      - label: I have read the README.md and understand the submission rules. 
    validations:
      required: true
  - type: textarea
  id: comment
  attributes:
    label: Relevant Information
    description: "comment box."
