name: Port Submission
description: Submit a candidate Android port for the PS Vita SO loader
title: "[Android Game Name]: "
labels: ["bug", "triage"]
assignees:
  - CatoTheYounger
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
